Commit 12-32-2019

diff --git a/themes/after-dark/bin/install b/themes/after-dark/bin/install
--- a/themes/after-dark/bin/install
+++ b/themes/after-dark/bin/install
@@ -1,15 +1,34 @@
 #!/bin/sh
 
+#
+# Copyright (C) 2019  Josh Habdas <jhabdas@protonmail.com>
+#
+# This file is part of After Dark.
+#
+# After Dark is free software: you can redistribute it and/or modify
+# it under the terms of the GNU Affero General Public License as published
+# by the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# After Dark is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Affero General Public License for more details.
+#
+# You should have received a copy of the GNU Affero General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+#
+
 validate_hugo () {
    # Exit with error if hugo is not installed
    if ! hash hugo 2>/dev/null ; then
-     echo "Error: After Dark requires Hugo version 0.44 or greater" >&2; exit 1
+     echo "Error: After Dark requires Hugo version 0.51 or greater" >&2; exit 1
    fi
 
    # Exit with error if not minimum required hugo version
-   re="v(0\d*\.([4-9][4-9]|[5-9])|[1-9]).*"
+   re="v(0\d*\.([5-9][1-9]|[6-9])|[1-9]).*"
    if ! hugo version | grep -qE "$re" ; then
-      echo "Error: After Dark requires Hugo version 0.44 or greater" >&2; exit 1
+      echo "Error: After Dark requires Hugo version 0.51 or greater" >&2; exit 1
    fi
 }
 
@@ -32,7 +51,7 @@ create_site () {
 download_theme () {
    echo "Downloading the latest version of After Dark ..."
    LATEST_META=$(wget -qO - https://registry.npmjs.org/after-dark/latest)
-   vers=$(echo "$LATEST_META" | egrep -o "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
+   vers=$(echo "$LATEST_META" | grep -oE "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
    mkdir -p themes/after-dark
    wget -qO - https://registry.npmjs.org/after-dark/-/after-dark-"$vers".tgz | tar --strip-components=1 -xz -C themes/after-dark
    echo "Version $vers downloaded to $SITE_DIR/themes/after-dark"
@@ -42,7 +61,7 @@ download_module () {
    [ -z "$1" ] && { echo "Error: Attempt to download undefined module" >&2; exit 1; }
    echo "Downloading $1 module for After Dark ..."
    meta=$(wget -qO - https://registry.npmjs.org/"$1"/latest)
-   vers=$(echo "$meta" | egrep -o "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
+   vers=$(echo "$meta" | grep -oE "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
    mkdir -p themes/"$1"
    wget -qO - https://registry.npmjs.org/"$1"/-/"$1"-"$vers".tgz | tar --strip-components=1 -xz -C themes/"$1"
    echo "Version $vers downloaded to $SITE_DIR/themes/$1"
@@ -55,13 +74,15 @@ baseurl = "https://domain.example" # Controls base URL sitewide
 languageCode = "en-US" # Controls site language
 title = "After Dark" # Homepage title and page title suffix
 paginate = 11 # Number of posts to show before paginating
+copyright = "Copyright &copy; Copyright Owner. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices
 
 # Controls default theme and theme components
 theme = [
-  "fractal-forest",
-  "after-dark"
+  "fractal-forest", # OBSD
+  "after-dark" # AGPL-3.0-or-later
 ]
 
+disableLiveReload = false # Optional, set true to disable live reload
 enableRobotsTXT = true # Suggested, enable robots.txt file
 
 pygmentsCodefences = true # Suggested, highlight fenced code blocks
@@ -74,13 +95,16 @@ footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
   description = "" # Suggested, controls default description meta
   author = "" # Optional, controls author name display on posts
   hide_author = false # Optional, set true to hide author name on posts
-  has_cookies = false # Optional, set true to disable cookie disclaimer
+  disable_csp = false # Optional, set true to disable content security policy
   images = [
     "https://source.unsplash.com/collection/983219/2000x1322"
   ] # Suggested, controls default Open Graph images
 
 [params.layout.menu.main]
   hidden = true # Optional, set false or remove to show section menu
+
+[params.layout.footer]
+  hidden = false # Optional, set true to hide footer
 
 [params.modules.fractal_forest]
   enabled = true # Optional, set false to disable module
